apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: health-worker-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: health-worker-api
    spec:
      containers:
      - name: app
        image: pir5/health-worker-api:latest
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: worker-conf
          mountPath: /etc/health-worker
      volumes:
      - name: worker-conf
        configMap:
          name: worker-conf
