apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: health-worker-register
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: health-worker-register
    spec:
      containers:
      - name: app
        image: pir5/health-worker:latest
        command: ["/health-worker"]
        args: ["register"]
        volumeMounts:
        - name: worker-conf
          mountPath: /etc/health-worker
      volumes:
      - name: worker-conf
        configMap:
          name: worker-conf
