apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: health-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: health-worker
    spec:
      containers:
      - name: app
        image: pir5/health-worker:latest
        command: ["/health-worker"]
        args: ["worker"]
        volumeMounts:
        - name: worker-toml
          mountPath: /etc/health-worker
      volumes:
      - name: worker-toml
        configMap:
          name: worker-toml
