apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: viron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: viron
    spec:
      containers:
      - name: app
        image: pir5/viron
        command: ["/health-worker"]
        args: ["register"]
        volumeMounts:
        - name: worker-toml
          mountPath: /etc/health-worker
      volumes:
      - name: worker-toml
        configMap:
          name: worker-toml
